name: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY
#url: http://brianmaierjr.github.com/long-haul
#url: http://0.0.0.0:4000/
baseurl: /long-haul
markdown: redcarpet
pygments: true
paginate: 3
paginate_path: "blog/page:num/"
permalink: /blog/:title/

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html 
