name: Long Haul
desctription: A minimal, long form template for Jekyll.
markdown: redcarpet
pygments: true

url: https://brianmaierjr.github.io
baseurl: /long-haul/

navigation:
 - title: Home
   url: {{ site.url }}{{ site.baseurl }}index.html
 - title: Articles
   url: {{ site.url }}{{ site.baseurl }}articles.html
 - title: About
   url: {{ site.url }}{{ site.baseurl }}about.html
 - title: Contact
   url: {{ site.url }}{{ site.baseurl }}contact.html 
