name: Long Haul
desctription: A minimal, long form template for Jekyll.
markdown: redcarpet
pygments: true
paginate: 3
paginate_path: "blog/page:num/"
url: https://brianmaierjr.github.io
baseurl: /long-haul/

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: https://brianmaierjr.github.io/long-haul/about.html
 - title: Contact
   url: https://brianmaierjr.github.io/long-haul/contact.html 
