name: Long Haul
desctription: A minimal, long form template for Jekyll.
markdown: redcarpet
pygments: true

url: https://brianmaierjr.github.io
baseurl: /long-haul/

navigation:
 - title: Home
   url: https://brianmaierjr.github.io/long-haul/index.html
 - title: Articles
   url: https://brianmaierjr.github.io/long-haul/articles.html
 - title: About
   url: https://brianmaierjr.github.io/long-haul/about.html
 - title: Contact
   url: https://brianmaierjr.github.io/long-haul/contact.html 
