name: Long Haul
desctription: A minimal, long form template for Jekyll.
markdown: redcarpet
pygments: true
paginate: 3
paginate_path: "blog/page:num/"
url: /long-haul
baseurl: http://brianmaierjr.github.com/long-haul

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html 
