name: Long Haul
desctription: A minimal, long form template for Jekyll.
markdown: redcarpet
pygments: true
paginate: 3
paginate_path: "blog/page:num/"
baseurl: https://brianmaierjr.github.io
url: /long-haul

navigation:
 - title: Home
   url: https://brianmaierjr.github.io/long-haul/index.html
 - title: About
   url: https://brianmaierjr.github.io/long-haul/about.html
 - title: Contact
   url: https://brianmaierjr.github.io/long-haul/contact.html 
