name: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY
url: http://brianmaierjr.github.com/long-haul
#url: http://0.0.0.0:4000/
markdown: redcarpet
pygments: true
paginate: 3
paginate_path: "{{ site.url }}/blog/page:num/"
permalink: "{{ site.url }}/blog/:title/"

navigation:
 - title: Home
   url: {{ site.url }}/index.html
 - title: About
   url: {{ site.url }}/about.html
 - title: Contact
   url: {{ site.url }}/contact.html 
