name: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://brianmaierjr.github.com/long-haul
baseurl: /long-haul
paginate_path: "http://brianmaierjr.github.com/long-haul/blog/page:num/"
permalink: http://brianmaierjr.github.com/long-haul/blog/:title/

markdown: redcarpet
pygments: true
paginate: 3

#baseurl: ""
#paginate_path: "/blog/page:num/"
#permalink: /blog/:title/

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about.html
 - title: Contact
   url: /contact.html 
