title: Biology 489, Herpetology
description: Herpetology at the University of Idaho Fall 2015

url: http://lukejharmon.github.io/herpclass/
baseurl: "/herpclass"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Syllabus
   url: /syllabus.html
 - title: Lecture
   url: /schedule.html
 - title: Lab
   url: /labSchedule.html
 - title: Contact
   url: /contact.html

social:
   github: lukejharmon
   twitter: lukejharmon
   facebook: lukejharmon
   email: lukeh@uidaho.edu

google_analytics: ""
